// Teste de navegador (Playwright): Jornada (XP, nível, missões, conquistas) e jogos novos
// (Caso do dia, Termo, Pares, Onde fica?). Usa conteúdo de exemplo se os arquivos de jogos estiverem vazios.
// Rode na raiz:   python3 -m http.server 8765 &   e   node curriculos/testes/jornada.js
const { chromium } = require('playwright');
const URL = process.env.APP_URL || 'http://localhost:8765/curriculos/app.html';
let falhas = 0; const ok = (c, m) => { console.log((c ? '  ✓ ' : '  ✗ ') + m); if (!c) falhas++; };
(async () => {
  const b = await chromium.launch(process.env.CHROMIUM ? { executablePath: process.env.CHROMIUM } : {}); const errs = [];
  const p = await b.newPage({ viewport: { width: 390, height: 840 } }); p.on('pageerror', e => errs.push(e.message));
  await p.goto(URL + '#/'); await p.waitForTimeout(700);
  await p.evaluate(() => {   // garante conteúdo mínimo para os jogos novos
    if (!JOGOS_DADOS.casos?.length) JOGOS_DADOS.casos = [{ id: 'cd-t', diagnostico: 'Malária', especialidade: 'infectologia', nivel: 1, pistas: ['p1', 'p2', 'p3', 'p4', 'p5'], opcoes: ['Dengue', 'Malária', 'Leptospirose', 'Febre amarela', 'Leishmaniose', 'Chikungunya'], explicacao: 'x', chave: 4 }];
    if (!JOGOS_DADOS.termo?.length) JOGOS_DADOS.termo = [{ palavra: 'FEBRE', exibir: 'febre', dica: 'sobe', definicao: 'x', area: 'clínica' }];
  });
  console.log('1) XP e nível');
  let r = await p.evaluate(() => { const qs = QUESTOES_BASE.filter(q => q.t === 'medicina').slice(0, 3); registrarResposta(qs[0], qs[0].c, 1, 'pratica'); registrarResposta(qs[1], (qs[1].c + 1) % 5, 1, 'pratica'); return docJornada().xp; });
  ok(r === 13, 'acerto +10, erro +3 (XP ' + r + ')');
  r = await p.evaluate(() => nivelDe(800).nome + '|' + nivelDe(799).nome + '|' + nivelDe(99999).nome);
  ok(r === 'Interno|Monitor|Lenda do plantão', 'níveis: ' + r);
  await p.evaluate(() => fecharFolha());
  console.log('2) Missões e conquistas');
  r = await p.evaluate(() => { const a = missoesDoDia().map(m => m.id), b = missoesDoDia().map(m => m.id); return { a, igual: a.join() === b.join(), q: a.filter(id => ['q15', 'q25', 'ac10'].includes(id)).length }; });
  ok(r.a.length === 3 && r.igual && r.q === 1, '3 missões fixas no dia, uma de questões: ' + r.a.join(','));
  r = await p.evaluate(() => { const qs = QUESTOES_BASE.filter(q => q.t === 'medicina').slice(10, 22); qs.forEach(q => registrarResposta(q, q.c, 1, 'pratica')); document.querySelectorAll('.folha').forEach(() => fecharFolha()); return !!docJornada().conq.q10; });
  ok(r, 'conquista "Primeiros passos" com 10 questões');
  await p.goto(URL + '#/jornada'); await p.waitForTimeout(300);
  ok(await p.locator('.missao').count() === 3 && await p.locator('.medalha-item').count() >= 20, 'página da jornada: 3 missões e as medalhas');
  console.log('3) Caso do dia');
  await p.goto(URL + '#/jogos/caso'); await p.waitForTimeout(300); await p.evaluate(() => fecharFolha()); await p.click('[data-act="jg-modo"][data-m="dia"]'); await p.waitForTimeout(200);
  ok(await p.locator('.pistas li.aberta').count() === 1, 'começa com 1 pista');
  await p.evaluate(() => { const r = JG.rodadas[0], c = casosDoDia().find(x => x.id === r.cid); [...document.querySelectorAll('[data-act="cd-palpite"]')].find(b => b.dataset.o !== c.diagnostico).click(); }); await p.waitForTimeout(100);
  ok(await p.locator('.pistas li.aberta').count() === 2, 'palpite errado revela a 2ª pista');
  await p.evaluate(() => { const r = JG.rodadas[0], c = casosDoDia().find(x => x.id === r.cid); [...document.querySelectorAll('[data-act="cd-palpite"]')].find(b => b.dataset.o === c.diagnostico).click(); }); await p.waitForTimeout(100);
  r = await p.evaluate(() => JG.pontos); ok(r === 40, 'acerto na 2ª pista = 40 pontos');
  await p.click('[data-act="jg-prox"]'); await p.waitForTimeout(150); await p.evaluate(() => document.querySelectorAll('.folha').forEach(() => fecharFolha()));
  await p.goto(URL + '#/jogos'); await p.goto(URL + '#/jogos/caso'); await p.waitForTimeout(300); JGreset = await p.evaluate(() => { JG.id = null; atualizar(); });
  ok(/já jogou o de hoje/.test(await p.innerText('#view')) && !(await p.$('[data-m="dia"]')), 'caso de hoje só uma vez por dia');
  console.log('4) Termo');
  r = await p.evaluate(() => [avaliarTermo('SOPRO', 'PULSO').join(''), avaliarTermo('EEEEE', 'FEBRE').join('')]);
  ok(r[0] === 'pnpnc' && r[1] === 'ncnnc', 'avaliação de letras (repetidas inclusive): ' + r.join(' '));
  await p.goto(URL + '#/jogos/termo'); await p.waitForTimeout(300); await p.evaluate(() => fecharFolha()); await p.click('[data-act="jg-modo"][data-m="treino"]'); await p.waitForTimeout(200);
  const w = await p.evaluate(() => JG.rodadas[0].w);
  await p.keyboard.type('abcde'); await p.keyboard.press('Enter'); await p.waitForTimeout(80);
  for (const l of w) await p.click(`[data-act="tm-letra"][data-l="${l}"]`); await p.click('[data-act="tm-enter"]'); await p.waitForTimeout(100);
  r = await p.evaluate(() => ({ ok: JG.rodadas[0].ok, n: JG.rodadas[0].tent.length, pts: JG.pontos }));
  ok(r.ok && r.n === 2 && r.pts === 50, 'teclado físico e na tela; acerto na 2ª = 50 pontos');
  console.log('5) Pares e Onde fica?');
  await p.goto(URL + '#/jogos/pares'); await p.waitForTimeout(300); await p.evaluate(() => fecharFolha()); await p.click('[data-act="jg-comecar"]'); await p.waitForTimeout(200);
  await p.evaluate(() => { const r = JG.rodadas[0]; const [e] = r.pares[0]; document.querySelector(`[data-act="pr-esq"][data-v="${CSS.escape(e)}"]`).click(); document.querySelector(`[data-act="pr-dir"][data-v="${CSS.escape(r.pares[1][1])}"]`).click(); });
  ok(await p.evaluate(() => JG.rodadas[0].erros === 1), 'par errado conta erro');
  await p.evaluate(() => { const r = JG.rodadas[0]; for (const [e, d] of r.pares) { document.querySelector(`[data-act="pr-esq"][data-v="${CSS.escape(e)}"]`)?.click(); document.querySelector(`[data-act="pr-dir"][data-v="${CSS.escape(d)}"]`)?.click(); } });
  ok(await p.evaluate(() => JG.rodadas[0].fim) && /Para fixar/i.test(await p.innerText('#view')), 'conjunto completo mostra "Para fixar"');
  await p.goto(URL + '#/jogos/anatomia'); await p.waitForTimeout(300); await p.evaluate(() => fecharFolha()); await p.click('[data-act="jg-comecar"]'); await p.waitForTimeout(200);
  r = await p.evaluate(() => { const r = JG.rodadas[0]; document.querySelector(`[data-org="${r.certo}"]`).dispatchEvent(new MouseEvent('click', { bubbles: true })); return JG.pontos; });
  ok(r === 10, 'tocar o órgão certo = 10 pontos');
  ok(await p.evaluate(() => PERGUNTAS_ANAT.every(([, o]) => ORGAOS[o] && document.querySelector(`[data-org="${o}"]`))), 'todo órgão das perguntas existe no mapa');
  console.log('6) XP pelos jogos');
  r = await p.evaluate(() => { const antes = docJornada().xp; terminarJogo(); return docJornada().xp - antes; });
  ok(r >= 8, 'fim de jogo dá XP (' + r + ')');
  console.log('7) Encerrar sem jogar não vale nada (M9)');
  for (const id of ['vf', 'triagem', 'milhao']) {
    await p.goto(URL + '#/jogos/' + id); await p.waitForTimeout(250); await p.evaluate(() => document.querySelectorAll('.folha').forEach(() => fecharFolha()));
    const antes = await p.evaluate(id => { const J = docJornada(), D = store.doc('jogos'); return { xp: J.xp, dia: J.dia.jogos, cont: J.cont.jogos || 0, n: D.n[id] || 0, conq: Object.keys(J.conq).length }; }, id);
    await p.click('[data-act="jg-comecar"]'); await p.waitForTimeout(150);
    await p.click(id === 'milhao' ? '[data-act="ml-parar"]' : '[data-act="jg-parar"]'); await p.waitForTimeout(150);
    const depois = await p.evaluate(id => { const J = docJornada(), D = store.doc('jogos'); return { xp: J.xp, dia: J.dia.jogos, cont: J.cont.jogos || 0, n: D.n[id] || 0, conq: Object.keys(J.conq).length, jg: JG.id, intro: !!document.querySelector('[data-act="jg-comecar"]') }; }, id);
    ok(JSON.stringify({ ...antes }) === JSON.stringify({ xp: depois.xp, dia: depois.dia, cont: depois.cont, n: depois.n, conq: depois.conq }) && depois.jg === null && depois.intro,
      `${id}: encerrar logo depois de começar não dá XP, partida, missão nem conquista e volta à abertura`);
  }
  r = await p.evaluate(() => { iniciarJogo('vf'); const q = JG.rodadas[0]; JG.resp = true; pontuar(q.verdade); const J = docJornada(), a = J.dia.jogos; terminarJogo(); return docJornada().dia.jogos - a; });
  ok(r === 1, 'com uma jogada, encerrar conta a partida');
  r = await p.evaluate(() => { const J = docJornada(), orig = missoesDoDia; J.missoes = { d: J.dia.d, ok: [] };
    missoesDoDia = () => ['t1', 't2', 't3'].map(id => ({ id, txt: id, meta: 1, v: () => 1 }));
    const a = J.dia.xp; try { conferirMissoes(J); } finally { missoesDoDia = orig; } return J.dia.xp - a; });
  ok(r === 150, 'XP das missões (3 × 40) e o bônus (+30) contam no XP de hoje: ' + r);
  console.log('8) Termo no celular e Onde fica? pelo teclado');
  const ctx2 = await b.newContext({ viewport: { width: 360, height: 740 }, hasTouch: true, isMobile: true }); const p2 = await ctx2.newPage(); p2.on('pageerror', e => errs.push(e.message));
  await p2.goto(URL + '#/jogos/termo'); await p2.waitForTimeout(600); await p2.evaluate(() => document.querySelectorAll('.folha').forEach(() => fecharFolha()));
  await p2.click('[data-act="jg-modo"][data-m="treino"]'); await p2.waitForTimeout(200);
  for (const l of 'ABCDE') await p2.click(`[data-act="tm-letra"][data-l="${l}"]`); await p2.click('[data-act="tm-enter"]'); await p2.waitForTimeout(250);
  r = await p2.evaluate(() => { const topo = document.querySelector('.topo').getBoundingClientRect().bottom, base = document.querySelector('.inferior').getBoundingClientRect().top;
    const env = document.querySelectorAll('.termo-linha')[0].getBoundingClientRect(), tec = document.querySelector('.teclado').getBoundingClientRect(), ts = [...document.querySelectorAll('.tecla')].map(t => t.getBoundingClientRect());
    return { visivel: env.top >= topo && env.bottom <= base && tec.top >= topo && tec.bottom <= base + 1, h: Math.min(...ts.map(t => t.height)), w: Math.min(...ts.map(t => t.width)), foco: document.activeElement?.classList.contains('tecla') }; });
  ok(r.visivel, 'Termo (360×740): tentativa enviada e teclado inteiros na tela, entre as barras');
  ok(r.h >= 40 && r.w >= 30, `teclas com alvo de toque: ${Math.round(r.w)}×${Math.round(r.h)} px (mín. 30×40)`);
  ok(!r.foco, 'toque na tecla da tela não prende o foco (Enter do teclado físico continua enviando)');
  await p2.goto(URL + '#/jogos/anatomia'); await p2.waitForTimeout(300); await p2.click('[data-act="jg-comecar"]'); await p2.waitForTimeout(200);
  r = await p2.evaluate(() => { const ps = [...document.querySelectorAll('.orgao')], nomes = Object.values(ORGAOS).map(n => n.toLowerCase());
    return { focaveis: ps.every(x => x.getAttribute('tabindex') === '0' && x.getAttribute('role') === 'button'), semResposta: ps.every(x => !nomes.some(n => (x.getAttribute('aria-label') + x.textContent).toLowerCase().includes(n))) }; });
  ok(r.focaveis && r.semResposta, 'Onde fica?: órgãos focáveis (Tab) e com rótulo de posição, sem o nome (não entrega a resposta)');
  await p2.focus('.orgao'); await p2.keyboard.press('Enter'); await p2.waitForTimeout(150);
  r = await p2.evaluate(() => ({ resp: JG.rodadas[0].resp != null, foco: document.activeElement?.dataset?.act }));
  ok(r.resp && r.foco === 'jg-prox', 'Enter no órgão focado responde e leva o foco para "Próxima"');
  await ctx2.close();
  ok(!errs.length, errs.length ? 'erros de JS: ' + errs.join(' | ') : 'Sem erros de JS');
  await b.close(); console.log(falhas ? `${falhas} FALHA(S)` : 'JORNADA E JOGOS NOVOS OK'); process.exit(falhas ? 1 : 0);
})();
let JGreset;
