#!/usr/bin/env python3
"""Gera triagem.json para o jogo "Plantão no PS" (Protocolo de Manchester)."""
import json
import random
from collections import Counter
from pathlib import Path

SAIDA = Path(__file__).with_name("triagem.json")


def s(PA=None, FC=None, FR=None, Sat=None, Tax=None, dor=None, gcs=15, hgt=None):
    return {"PA": PA, "FC": FC, "FR": FR, "SatO2": Sat, "Tax": Tax,
            "dor": dor, "glasgow": gcs, "HGT": hgt}


# (nome, avatar, queixa, sinais, cor, discriminador, porque, fluxograma)
P = [
    # ---------------- VERMELHO (15) ----------------
    ("Kauã, 9 anos", "crianca", "Tiraram ele do rio desacordado. Tá roxinho e respirando fraquinho.",
     s(None, 48, 6, 78, 35.2, None, 8), "vermelho", "Respiração inadequada",
     "Afogamento com FR 6 e SatO2 78%: a respiração não sustenta a vida. Atendimento imediato.", "Dispneia em criança"),
    ("Gleiciane, 12 anos", "crianca", "O cabelo dela enrolou no motor do barco. Tá sangrando muito da cabeça!",
     s("80x40", 142, 28, 95, 35.8, 10, 14), "vermelho", "Hemorragia exsanguinante",
     "Escalpelamento com sangramento que não para e sinais de choque. Risco de morte: sala vermelha já.", "Feridas"),
    ("Luana, 23 anos", "mulher", "Tô com dengue. Hoje fiquei gelada, tonta, quase desmaiei.",
     s("70x50", 132, 26, 95, 36.0, 6, 14), "vermelho", "Choque",
     "Dengue grave: hipotensão, taquicardia e pele fria. A febre sumiu, mas é a fase crítica.", "Mal-estar em adulto"),
    ("Ravi, 3 anos", "crianca", "Ele tá se tremendo todo e não para! Tava com febre.",
     s(None, 162, 30, 88, 39.4, None, None), "vermelho", "Convulsionando",
     "Crise convulsiva em curso é sempre vermelho, independente da causa (aqui, febre).", "Convulsões"),
    ("Jucimara, 34 anos", "mulher", "Comi camarão. A garganta tá fechando e o rosto inchou todo.",
     s("80x50", 128, 30, 89, 36.7, 5, 15), "vermelho", "Estridor / via aérea comprometida",
     "Anafilaxia com estridor: a via aérea pode fechar em minutos. Adrenalina imediata.", "Alergia"),
    ("Benedito, 62 anos", "idoso", "Cobra picou ele na roça. A perna inchou e agora tá mole e suando frio.",
     s("70x40", 130, 26, 93, 35.9, 9, 13), "vermelho", "Choque",
     "Acidente ofídico com choque. A dor intensa daria laranja, mas o choque vem antes: vermelho.", "Mordeduras e picadas"),
    ("Railson, 22 anos", "homem", "Caiu de moto. Tá engasgando com sangue na boca, fazendo barulho.",
     s("110x70", 124, 34, 84, 36.2, None, 9), "vermelho", "Via aérea comprometida",
     "Trauma de face com ruído e sangue na via aérea. Via aérea é a 1ª prioridade (A do ABCDE).", "Grande traumatismo"),
    ("Deusimar, 45 anos", "mulher", "Minha asma atacou. Não consigo nem falar...",
     s("140x90", 138, 36, 84, 36.8, None, 15), "vermelho", "Respiração inadequada",
     "Asma grave: fala entrecortada, FR 36 e SatO2 84%. Esforço que não mantém a oxigenação.", "Asma"),
    ("Enzo, 4 meses", "bebe", "Ele tá quietinho demais, não acorda pra mamar e tá frio.",
     s(None, 190, 60, 91, 35.5, None, None), "vermelho", "Choque",
     "Armadilha: bebê \"calmo\" com FC 190, frio e hipoativo está em choque (provável sepse).", "Mal-estar em criança"),
    ("Erisvaldo, 40 anos", "homem", "Cortei a coxa com o terçado. O sangue tá jorrando!",
     s("90x50", 124, 24, 97, 36.3, 8, 15), "vermelho", "Hemorragia exsanguinante",
     "Sangue em jato que não para com pressão: lesão arterial. Controle do sangramento é imediato.", "Feridas"),
    ("Manoel, 70 anos", "idoso", "Vomitou muito sangue e ficou branco que nem papel.",
     s("76x40", 128, 26, 94, 35.8, 4, 14), "vermelho", "Choque",
     "Hemorragia digestiva alta com hipotensão e taquicardia. Choque hipovolêmico.", "Hemorragia digestiva"),
    ("Raimundo, 58 anos", "homem", "Dor forte no peito e tô todo suado, frio, sem força.",
     s("78x50", 118, 24, 92, 36.1, 9, 15), "vermelho", "Choque",
     "Dor precordial daria laranja, mas há choque (provável IAM com choque cardiogênico): vermelho.", "Dor torácica"),
    ("Oziel, 27 anos", "homem", "Tá com malária e começou a se debater agora, com os olhos virados.",
     s("100x60", 136, 28, 91, 40.2, None, None), "vermelho", "Convulsionando",
     "Convulsão ativa em paciente com malária: pensar em malária grave (cerebral).", "Convulsões"),
    ("Ivanilda, 19 anos", "gestante", "Grávida de 8 meses. Tá se batendo toda, tendo uma convulsão!",
     s("170x115", 124, 24, 93, 36.9, None, None), "vermelho", "Convulsionando",
     "Gestante convulsionando com PA alta: eclâmpsia. Vermelho e sulfato de magnésio.", "Convulsões"),
    ("Francisca, 81 anos", "idosa", "Cansaço muito forte, os lábios tão roxos e ela não responde direito.",
     s("100x60", 118, 38, 80, 37.9, None, 12), "vermelho", "Respiração inadequada",
     "FR 38, SatO2 80% e cianose: falência respiratória. Não espere a febre para agir.", "Dispneia em adulto"),

    # ---------------- LARANJA (20) ----------------
    ("Tarcísio, 52 anos", "homem", "Dor no peito em aperto, que corre pro braço esquerdo, há meia hora.",
     s("150x90", 96, 18, 97, 36.6, 6, 15), "laranja", "Dor precordial",
     "Dor sugestiva de origem cardíaca é laranja mesmo com dor moderada e sinais vitais normais. ECG em 10 min.", "Dor torácica"),
    ("Adenor, 76 anos", "idoso", "Dor na barriga que vai pras costas. Não é nada, minha filha que trouxe.",
     s("130x80", 88, 18, 97, 36.5, 6, 15), "laranja", "Dor irradiada para as costas",
     "Armadilha: idoso com sinais normais. Dor abdominal irradiada ao dorso pode ser aneurisma de aorta.", "Dor abdominal em adulto"),
    ("Rosilene, 30 anos", "mulher", "Dor do lado das costas, não aguento, já vomitei de tanta dor.",
     s("130x80", 92, 18, 98, 36.7, 9, 15), "laranja", "Dor intensa (8–10)",
     "Armadilha: sinais vitais normais, mas dor 9/10 já é laranja (provável cólica renal).", "Dor abdominal em adulto"),
    ("Josué, 35 anos", "homem", "Pisei numa arraia no igarapé. A dor tá insuportável!",
     s("140x90", 108, 22, 98, 36.6, 10, 15), "laranja", "Dor intensa (8–10)",
     "Picada de arraia causa dor muito intensa. Dor 10/10 = laranja. Água morna alivia.", "Mordeduras e picadas"),
    ("Maria das Graças, 67 anos", "idosa", "A boca entortou e o braço direito não mexe desde agora cedo.",
     s("180x100", 84, 18, 96, 36.4, 0, 15), "laranja", "Déficit neurológico agudo",
     "Suspeita de AVC: déficit focal agudo é laranja. Tempo é cérebro (janela de trombólise).", "Mal-estar em adulto"),
    ("Edivaldo, 60 anos", "homem", "Diabético, tomou insulina e não comeu. Tá suando e confuso.",
     s("130x80", 104, 18, 98, 36.2, 0, 14, 42), "laranja", "Hipoglicemia (HGT < 54 mg/dL)",
     "HGT 42: hipoglicemia. Confusão melhora com glicose. Sempre medir HGT em alteração de consciência.", "Diabetes"),
    ("Iracema, 41 anos", "mulher", "Tá com malária. Hoje começou a falar coisa sem sentido.",
     s("110x70", 112, 22, 96, 39.8, 3, 13), "laranja", "Alteração do nível de consciência",
     "Glasgow 13 em quem tem malária: sinal de gravidade. A consciência alterada define o laranja.", "Mal-estar em adulto"),
    ("Cleidiane, 55 anos", "mulher", "Falta de ar há 2 dias, tossindo muito catarro.",
     s("130x80", 108, 28, 88, 38.2, 3, 15), "laranja", "SatO2 muito baixa (< 90%)",
     "SatO2 88% em ar ambiente é muito baixa: laranja, mesmo sem outros sinais graves.", "Dispneia em adulto"),
    ("Socorro, 48 anos", "mulher", "O coração disparou do nada. Tá batendo aqui na garganta.",
     s("110x70", 168, 20, 97, 36.5, 2, 15), "laranja", "Pulso anormal",
     "FC 168 em repouso é pulso anormal: laranja. Fazer ECG logo (provável taquiarritmia).", "Palpitações"),
    ("Pedro, 6 anos", "crianca", "Febre muito alta, o termômetro deu mais de 41!",
     s(None, 150, 30, 97, 41.2, 3, 15), "laranja", "Muito quente (≥ 41 °C)",
     "Temperatura ≥ 41 °C é \"muito quente\": laranja. Entre 38,5 e 41 seria amarelo.", "Mal-estar em criança"),
    ("Jéssica, 19 anos", "mulher", "Dengue há 4 dias. A febre passou, mas agora a barriga dói demais.",
     s("110x70", 100, 20, 98, 36.8, 8, 15), "laranja", "Dor intensa (8–10)",
     "Armadilha: a febre sumiu, mas dor abdominal intensa é sinal de alarme da dengue. Dor 8 = laranja.", "Dor abdominal em adulto"),
    ("Raimunda, 28 anos", "gestante", "Grávida de 7 meses. Dor de cabeça forte e vendo pontinhos brilhando.",
     s("168x112", 96, 18, 98, 36.6, 8, 15), "laranja", "Dor intensa (8–10)",
     "Dor intensa = laranja. Gestante com cefaleia, escotomas e PA alta: pensar em pré-eclâmpsia grave.", "Cefaleia"),
    ("Elielson, 33 anos", "homem", "Jararaca picou meu pé. Tá inchando e doendo muito.",
     s("130x80", 98, 20, 98, 36.7, 9, 15), "laranja", "Dor intensa (8–10)",
     "Sinais vitais estáveis, mas dor 9/10: laranja. Soro antiofídico sem demora.", "Mordeduras e picadas"),
    ("Yasmin, 12 anos", "crianca", "Quase se afogou na praia da Ponta Negra. Tá tossindo muito.",
     s("110x70", 118, 32, 89, 36.4, 2, 15), "laranja", "SatO2 muito baixa (< 90%)",
     "Afogamento com SatO2 89%: muito baixa. Consciente e falando, mas precisa de O2 já.", "Dispneia em criança"),
    ("Wellington, 17 anos", "homem", "Sou diabético. Vomitando, respirando fundo, hálito de fruta.",
     s("100x60", 118, 30, 98, 36.9, 5, 15, 480), "laranja", "Hiperglicemia com cetose",
     "HGT alto com respiração de Kussmaul e hálito cetônico: cetoacidose. Laranja.", "Diabetes"),
    ("Antônio, 70 anos", "idoso", "Caiu da rede, bateu a cabeça e ficou meio confuso.",
     s("150x90", 80, 18, 97, 36.5, 3, 13), "laranja", "Alteração do nível de consciência",
     "Glasgow 13 após trauma craniano: laranja. Idoso tem mais risco de hematoma.", "Traumatismo cranioencefálico"),
    ("Kleber, 25 anos", "homem", "Desloquei o ombro no futebol. A dor tá horrível.",
     s("130x80", 104, 20, 99, 36.5, 9, 15), "laranja", "Dor intensa (8–10)",
     "Luxação com dor 9/10: dor intensa = laranja, mesmo com sinais vitais bons.", "Problemas em extremidades"),
    ("Ana Clara, 2 anos", "crianca", "Ela tá bem calminha, só dorme. Nem chora mais.",
     s(None, 160, 36, 96, 39.0, None, 13), "laranja", "Alteração do nível de consciência",
     "Armadilha: criança \"quieta demais\" com febre é sonolência, não calma. Consciência alterada = laranja.", "Mal-estar em criança"),
    ("Marcos, 44 anos", "homem", "Dor de cabeça que veio de repente. A pior da minha vida.",
     s("160x95", 90, 18, 98, 36.6, 10, 15), "laranja", "Dor intensa (8–10)",
     "Dor 10/10 = laranja. Cefaleia súbita \"a pior da vida\" lembra hemorragia subaracnoide.", "Cefaleia"),
    ("Tainá, 8 anos", "crianca", "Derrubou a panela de água quente no braço.",
     s(None, 130, 26, 99, 36.8, 9, 15), "laranja", "Dor intensa (8–10)",
     "Queimadura com dor 9/10: laranja. Analgesia e resfriar com água corrente.", "Queimaduras"),

    # ---------------- AMARELO (25) ----------------
    ("Valdeci, 38 anos", "homem", "Febre com tremedeira dia sim, dia não. Trabalho no garimpo.",
     s("120x70", 104, 20, 97, 39.2, 3, 15), "amarelo", "Quente (38,5–40,9 °C)",
     "Febre ≥ 38,5 °C = quente: amarelo. Garimpo + febre periódica: pedir gota espessa (malária).", "Mal-estar em adulto"),
    ("Kelly, 26 anos", "mulher", "Tô com dengue. Nada para no estômago, já vomitei umas 8 vezes.",
     s("110x70", 98, 18, 98, 37.4, 4, 15), "amarelo", "Vômitos persistentes",
     "Vômitos persistentes: amarelo. Na dengue, também é sinal de alarme: hidratar e reavaliar.", "Diarreia e vômitos"),
    ("Sebastião, 50 anos", "homem", "Dor forte na lombar desde ontem, quando peguei peso.",
     s("130x80", 84, 16, 98, 36.5, 6, 15), "amarelo", "Dor moderada (5–7)",
     "Dor 6/10 é moderada: amarelo. Sem déficit neurológico nem sinais de gravidade.", "Dor lombar"),
    ("Nazaré, 72 anos", "idosa", "Tosse e cansaço há 3 dias.",
     s("130x80", 96, 22, 93, 37.8, 2, 15), "amarelo", "SatO2 baixa (< 95%)",
     "SatO2 93%: baixa (90–94%) = amarelo. Abaixo de 90% seria laranja.", "Dispneia em adulto"),
    ("Ruan, 16 anos", "homem", "Levei uma bolada na cabeça e apaguei uns segundos. Já tô bem.",
     s("120x70", 80, 16, 99, 36.5, 3, 15), "amarelo", "História de inconsciência",
     "Armadilha: está bem agora, mas perdeu a consciência após trauma. Isso já é amarelo.", "Traumatismo cranioencefálico"),
    ("Miguel, 5 anos", "crianca", "Febre alta desde ontem, deu 39 e pouco. Tá comendo pouco.",
     s(None, 130, 26, 98, 39.3, 2, 15), "amarelo", "Quente (38,5–40,9 °C)",
     "Febre ≥ 38,5 °C com criança ativa: quente = amarelo.", "Mal-estar em criança"),
    ("Nilzete, 39 anos", "mulher", "Cortei a mão no vidro. Já apertei com pano e não para de sangrar.",
     s("120x80", 92, 18, 99, 36.4, 4, 15), "amarelo", "Hemorragia menor incontrolável",
     "Sangramento pequeno que não para com compressão: amarelo. Se fosse em jato, vermelho.", "Feridas"),
    ("Joana, 45 anos", "mulher", "Caí na escada do flutuante e o punho ficou torto.",
     s("130x80", 90, 18, 99, 36.5, 6, 15), "amarelo", "Dor moderada (5–7)",
     "Provável fratura, mas a dor é 6/10: moderada = amarelo. Imobilizar e analgesia.", "Problemas em extremidades"),
    ("Carlos, 58 anos", "homem", "Sou diabético. A glicemia deu 400 no aparelho de casa.",
     s("140x90", 88, 16, 98, 36.6, 0, 15, 410), "amarelo", "Hiperglicemia (HGT > 300 mg/dL)",
     "HGT alto sem sinais de cetose (sem vômito nem Kussmaul): amarelo.", "Diabetes"),
    ("Priscila, 24 anos", "gestante", "Grávida de 32 semanas. A barriga endurece e dói nas costas.",
     s("120x70", 90, 18, 99, 36.6, 5, 15), "amarelo", "Dor moderada (5–7)",
     "Dor 5/10 = moderada: amarelo. Avaliar trabalho de parto prematuro.", "Gravidez"),
    ("Davi, 4 anos", "crianca", "Tá chorando de dor no ouvido desde a madrugada.",
     s(None, 120, 24, 99, 38.0, 6, 15), "amarelo", "Dor moderada (5–7)",
     "Otite com dor 6/10: moderada = amarelo. Febre de 38,0 sozinha não subiria a cor.", "Problemas de ouvido"),
    ("Luiz, 80 anos", "idoso", "Febre e tosse com catarro amarelo há 2 dias.",
     s("130x80", 100, 22, 95, 38.8, 2, 15), "amarelo", "Quente (38,5–40,9 °C)",
     "Temperatura 38,8 °C = quente: amarelo. SatO2 95% ainda não é baixa.", "Mal-estar em adulto"),
    ("Samara, 20 anos", "mulher", "Tô com chiado no peito, a bombinha não tá resolvendo.",
     s("120x80", 104, 24, 94, 36.7, 0, 15), "amarelo", "SatO2 baixa (< 95%)",
     "Asma com SatO2 94% e fala normal: amarelo. Reavaliar após nebulização.", "Asma"),
    ("Heitor, 7 anos", "crianca", "Vomita tudo desde cedo, até água. Já foram umas 6 vezes.",
     s(None, 118, 22, 99, 37.2, 3, 15), "amarelo", "Vômitos persistentes",
     "Vômitos que não param: amarelo, pelo risco de desidratação.", "Diarreia e vômitos"),
    ("Thiago, 21 anos", "homem", "Dor em volta do umbigo que desceu pro lado direito.",
     s("120x80", 96, 18, 99, 37.8, 6, 15), "amarelo", "Dor moderada (5–7)",
     "Dor 6/10: amarelo. A história lembra apendicite, mas a cor segue o discriminador.", "Dor abdominal em adulto"),
    ("Érica, 31 anos", "mulher", "Acho que é dengue: febre de 38,9, dor no corpo e atrás dos olhos.",
     s("120x80", 98, 18, 99, 38.9, 4, 15), "amarelo", "Quente (38,5–40,9 °C)",
     "Febre 38,9 °C = quente: amarelo. Sem sinais de alarme, mas a febre já define a cor.", "Mal-estar em adulto"),
    ("Josiane, 29 anos", "mulher", "O cachorro do vizinho mordeu minha perna.",
     s("120x80", 92, 18, 99, 36.6, 5, 15), "amarelo", "Dor moderada (5–7)",
     "Mordedura com dor 5/10: moderada = amarelo. Lembrar da profilaxia da raiva.", "Mordeduras e picadas"),
    ("Deise, 36 anos", "mulher", "Queimei a mão no óleo quente da fritura.",
     s("120x80", 94, 18, 99, 36.5, 6, 15), "amarelo", "Dor moderada (5–7)",
     "Queimadura pequena com dor 6/10: amarelo. Com dor 8 ou mais, seria laranja.", "Queimaduras"),
    ("Caio, 10 anos", "crianca", "Caiu da bicicleta. O joelho inchou e ele não quer pisar.",
     s(None, 104, 20, 99, 36.6, 7, 15), "amarelo", "Dor moderada (5–7)",
     "Dor 7/10 ainda é moderada: amarelo. A partir de 8, laranja.", "Problemas em extremidades"),
    ("Lucineide, 42 anos", "mulher", "Dor de cabeça há 2 dias que não passa com dipirona.",
     s("130x80", 80, 16, 99, 36.5, 6, 15), "amarelo", "Dor moderada (5–7)",
     "Cefaleia com dor 6/10, sem sinais neurológicos: moderada = amarelo.", "Cefaleia"),
    ("Sofia, 8 meses", "bebe", "Tosse, nariz entupido e tá cansadinha. Mama menos.",
     s(None, 150, 50, 93, 37.6, None, 15), "amarelo", "SatO2 baixa (< 95%)",
     "Bronquiolite com SatO2 93%: baixa = amarelo. Vigiar esforço respiratório.", "Dispneia em criança"),
    ("Francinaldo, 34 anos", "homem", "Depois da gripe, dói o peito quando eu respiro fundo.",
     s("120x80", 90, 20, 97, 37.6, 5, 15), "amarelo", "Dor pleurítica",
     "Dor que piora com a respiração é pleurítica: amarelo. Dor em aperto (precordial) seria laranja.", "Dor torácica"),
    ("Dona Zefa, 84 anos", "idosa", "Ela só tá fraca, meio caidinha. Não reclama de nada.",
     s("120x70", 102, 20, 96, 38.6, 0, 15), "amarelo", "Quente (38,5–40,9 °C)",
     "Armadilha: queixa vaga, mas Tax 38,6 °C = amarelo. Idoso infectado nem sempre tem sintomas típicos.", "Mal-estar em adulto"),
    ("Adriana, 27 anos", "gestante", "Grávida de 10 semanas. Vomito o dia todo, não paro nada.",
     s("110x70", 100, 18, 99, 36.7, 2, 15), "amarelo", "Vômitos persistentes",
     "Vômitos persistentes na gestação (hiperêmese): amarelo.", "Gravidez"),
    ("Osmar, 74 anos", "idoso", "Não consigo urinar desde ontem. A barriga tá estufada.",
     s("150x90", 92, 18, 97, 36.6, 7, 15), "amarelo", "Dor moderada (5–7)",
     "Retenção urinária com dor 7/10: moderada = amarelo. Sondagem alivia rápido.", "Problemas urinários"),

    # ---------------- VERDE (20) ----------------
    ("Marinalva, 33 anos", "mulher", "Ai, vou morrer! Torci o pé na calçada, socorro!",
     s("130x80", 96, 20, 99, 36.5, 3, 15), "verde", "Dor leve recente",
     "Armadilha: queixa dramática, mas dor 3/10 e sinais normais. Sem discriminador maior: verde.", "Problemas em extremidades"),
    ("Jefferson, 28 anos", "homem", "Febrezinha e dor no corpo desde ontem.",
     s("120x80", 88, 16, 99, 37.9, 2, 15), "verde", "Febril (37,5–38,4 °C)",
     "Tax 37,9 °C: febril, abaixo de 38,5. Sem outros achados: verde.", "Mal-estar em adulto"),
    ("Alessandra, 25 anos", "mulher", "Dor de garganta pra engolir desde anteontem.",
     s("110x70", 84, 16, 99, 37.3, 3, 15), "verde", "Dor leve recente",
     "Dor 3/10 com início há 2 dias: dor leve recente = verde.", "Dor de garganta"),
    ("Moisés, 46 anos", "homem", "Coriza e tosse há 2 dias. Queria ver se é gripe.",
     s("120x80", 80, 16, 98, 37.0, 0, 15), "verde", "Problema recente (< 7 dias)",
     "Sintoma recente sem febre, dor ou falta de ar: verde.", "Mal-estar em adulto"),
    ("Luciano, 37 anos", "homem", "Cortei o dedo com a faca. Já parou de sangrar.",
     s("120x80", 80, 16, 99, 36.5, 2, 15), "verde", "Dor leve recente",
     "Ferida pequena, sangramento controlado, dor 2/10: verde.", "Feridas"),
    ("Bianca, 19 anos", "mulher", "Virei o pé no vôlei ontem. Tá um pouco inchado.",
     s("110x70", 78, 16, 99, 36.4, 4, 15), "verde", "Dor leve recente",
     "Dor 4/10 ainda é leve (1–4): verde. Com dor 5 seria amarelo.", "Problemas em extremidades"),
    ("Zé Carlos, 52 anos", "homem", "Uma abelha me picou no braço. Tá vermelho e coçando.",
     s("130x80", 82, 16, 99, 36.6, 2, 15), "verde", "Dor leve recente",
     "Reação local, sem falta de ar ou inchaço no rosto: verde.", "Mordeduras e picadas"),
    ("Paulo Sérgio, 40 anos", "homem", "Tenho um furúnculo na perna que tá doendo.",
     s("130x80", 80, 16, 99, 37.1, 3, 15), "verde", "Infecção local",
     "Abscesso pequeno, sem febre alta nem sinais sistêmicos: verde.", "Infecções locais e abscessos"),
    ("Isabelly, 3 anos", "crianca", "Vomitou 2 vezes e tá com cocô mole. Mas tá brincando.",
     s(None, 110, 24, 99, 37.2, None, 15), "verde", "Vômitos",
     "Vômitos que não são persistentes, criança ativa e hidratada: verde.", "Diarreia e vômitos"),
    ("Cláudio, 31 anos", "homem", "Dor no ouvido desde ontem depois de tomar banho de rio.",
     s("120x80", 76, 14, 99, 36.6, 3, 15), "verde", "Dor leve recente",
     "Dor 3/10 com início recente: verde.", "Problemas de ouvido"),
    ("Keila, 22 anos", "mulher", "O olho tá vermelho e remelando desde hoje cedo.",
     s("110x70", 76, 14, 99, 36.5, 1, 15), "verde", "Olho vermelho",
     "Olho vermelho sem trauma, dor intensa ou perda de visão: verde (provável conjuntivite).", "Problemas oftalmológicos"),
    ("Rayane, 26 anos", "mulher", "Tô com falta de ar e as mãos formigando depois de uma briga em casa.",
     s("130x80", 102, 24, 99, 36.6, 0, 15), "verde", "Problema recente (< 7 dias)",
     "Armadilha: parece grave, mas SatO2 99% e sem dor ou alteração de consciência. Crise de ansiedade: verde.", "Dispneia em adulto"),
    ("Evandro, 29 anos", "homem", "Dor de dente desde ontem, latejando um pouco.",
     s("120x80", 80, 16, 99, 36.6, 4, 15), "verde", "Dor leve recente",
     "Dor 4/10 com início recente: verde.", "Problemas dentários"),
    ("Mirian, 35 anos", "mulher", "Ardência pra urinar desde ontem e vontade toda hora.",
     s("120x80", 80, 16, 99, 37.2, 3, 15), "verde", "Dor leve recente",
     "Provável cistite, sem febre alta nem dor lombar: verde.", "Problemas urinários"),
    ("Lorena, 1 ano", "bebe", "Caiu do sofá, chorou na hora e já tá brincando. Tô desesperada!",
     s(None, 120, 28, 99, 36.6, None, 15), "verde", "Problema recente (< 7 dias)",
     "Armadilha: mãe aflita, mas o bebê chorou logo, está ativo e sem perda de consciência: verde.", "Traumatismo cranioencefálico"),
    ("Gabriel, 11 anos", "crianca", "Pipocou umas bolinhas no braço que coçam depois do carapanã.",
     s(None, 90, 18, 99, 36.5, 1, 15), "verde", "Problema recente (< 7 dias)",
     "Lesões de pele recentes, sem febre nem sinais de alergia grave: verde.", "Erupções cutâneas"),
    ("Hellen, 30 anos", "mulher", "Febre de 38 e dor atrás dos olhos desde ontem. Será dengue?",
     s("120x80", 90, 16, 99, 38.0, 3, 15), "verde", "Febril (37,5–38,4 °C)",
     "Suspeita de dengue sem sinais de alarme e Tax 38,0 (abaixo de 38,5): verde.", "Mal-estar em adulto"),
    ("Roberto, 48 anos", "homem", "Travou as costas carregando rancho ontem. Dói um pouco.",
     s("130x80", 80, 16, 99, 36.6, 4, 15), "verde", "Dor leve recente",
     "Lombalgia com dor 4/10 e início ontem: verde.", "Dor lombar"),
    ("Silvana, 57 anos", "mulher", "Bati o braço na porta e ficou roxo.",
     s("130x80", 78, 16, 99, 36.4, 3, 15), "verde", "Dor leve recente",
     "Hematoma com dor leve e movimento normal: verde.", "Problemas em extremidades"),
    ("Thaís, 23 anos", "gestante", "Grávida de 20 semanas. Corrimento e coceira há uns dias.",
     s("110x70", 84, 16, 99, 36.5, 1, 15), "verde", "Problema recente (< 7 dias)",
     "Gestante sem sangramento, dor ou PA alta. Queixa recente e leve: verde.", "Gravidez"),

    # ---------------- AZUL (10) ----------------
    ("Genésio, 66 anos", "idoso", "Vim só renovar a receita do remédio da pressão.",
     s("138x88", 76, 16, 98, 36.4, 0, 15), "azul", "Sem discriminadores (não urgente)",
     "Sem queixa aguda e sinais estáveis: azul. Pode ir para a UBS.", "Mal-estar em adulto"),
    ("Célia, 34 anos", "mulher", "Preciso de atestado. Tive diarreia semana passada, já passou.",
     s("110x70", 74, 14, 99, 36.5, 0, 15), "azul", "Sem discriminadores (não urgente)",
     "Problema já resolvido, sem sintomas agora: azul.", "Diarreia e vômitos"),
    ("Aldenora, 63 anos", "idosa", "Dor no joelho faz mais de um ano. Hoje tá igual.",
     s("130x80", 74, 16, 98, 36.4, 3, 15), "azul", "Problema não recente, sem piora",
     "Dor leve crônica, sem mudança: não é \"recente\", então azul.", "Problemas em extremidades"),
    ("Rafael, 30 anos", "homem", "Vim mostrar o exame que o doutor pediu.",
     s("120x80", 72, 14, 99, 36.5, 0, 15), "azul", "Sem discriminadores (não urgente)",
     "Demanda administrativa sem queixa: azul.", "Mal-estar em adulto"),
    ("Pâmela, 17 anos", "mulher", "Tenho uma verruga na mão faz uns meses.",
     s("110x70", 76, 14, 99, 36.4, 0, 15), "azul", "Problema não recente, sem piora",
     "Lesão antiga, sem dor ou inflamação: azul.", "Erupções cutâneas"),
    ("Dorival, 55 anos", "homem", "Faço curativo todo dia aqui. Hoje é dia de trocar.",
     s("130x80", 78, 16, 98, 36.6, 1, 15), "azul", "Sem discriminadores (não urgente)",
     "Curativo programado, sem sinais de infecção: azul.", "Feridas"),
    ("Neide, 47 anos", "mulher", "Quero tomar a vacina da febre amarela, vou viajar.",
     s("120x80", 74, 14, 99, 36.5, 0, 15), "azul", "Sem discriminadores (não urgente)",
     "Sem queixa clínica: azul. Encaminhar para a sala de vacina.", "Mal-estar em adulto"),
    ("Igor, 26 anos", "homem", "Meu cabelo tá caindo muito faz uns 3 meses.",
     s("120x80", 70, 14, 99, 36.4, 0, 15), "azul", "Problema não recente, sem piora",
     "Queixa crônica e estável: azul.", "Mal-estar em adulto"),
    ("Joelma, 9 anos", "crianca", "Ela tem umas manchas brancas no rosto há meses.",
     s(None, 90, 18, 99, 36.5, 0, 15), "azul", "Problema não recente, sem piora",
     "Manchas antigas, sem sintomas agudos: azul. Avaliar na UBS.", "Erupções cutâneas"),
    ("Gerson, 71 anos", "idoso", "Dor de cabeça faz tempo, todo dia um pouquinho. Hoje tá igual.",
     s("130x80", 72, 16, 98, 36.5, 2, 15), "azul", "Problema não recente, sem piora",
     "Armadilha: \"dor de cabeça\" assusta, mas é antiga, leve e sem mudança: azul.", "Cefaleia"),
]

CORES = {"vermelho": 15, "laranja": 20, "amarelo": 25, "verde": 20, "azul": 10}
AVATARES = {"homem", "mulher", "idoso", "idosa", "crianca", "bebe", "gestante"}


def main():
    random.seed(2026)
    random.shuffle(P)
    itens = []
    for i, (nome, av, q, sv, cor, disc, pq, fl) in enumerate(P, 1):
        itens.append({"id": f"tr-{i:03d}", "nome": nome, "avatar": av, "queixa": q,
                      "sinais": sv, "cor": cor, "discriminador": disc,
                      "porque": pq, "fluxograma": fl})

    # validação
    assert len(itens) == 90, len(itens)
    assert len({x["id"] for x in itens}) == 90
    cont = Counter(x["cor"] for x in itens)
    assert dict(cont) == CORES, cont
    campos = ["id", "nome", "avatar", "queixa", "sinais", "cor",
              "discriminador", "porque", "fluxograma"]
    for x in itens:
        assert list(x) == campos, x["id"]
        assert x["avatar"] in AVATARES, x
        assert len(x["queixa"]) <= 110, (x["id"], len(x["queixa"]))
        assert len(x["discriminador"]) <= 60, (x["id"], x["discriminador"])
        assert len(x["porque"]) <= 200, (x["id"], len(x["porque"]))
        assert set(x["sinais"]) == {"PA", "FC", "FR", "SatO2", "Tax", "dor", "glasgow", "HGT"}
        d = x["sinais"]["dor"]
        assert d is None or 0 <= d <= 10
        for k in ("nome", "queixa", "discriminador", "porque", "fluxograma"):
            assert x[k].strip(), (x["id"], k)

    SAIDA.write_text(json.dumps(itens, ensure_ascii=False, indent=1) + "\n", encoding="utf-8")
    print("OK", len(itens), dict(cont))


if __name__ == "__main__":
    main()
