#!/usr/bin/env python3
"""Gera curriculos/jogos/pares.json (jogo "Pares") e valida o conteúdo.

Cada conjunto: 10 pares 1-para-1 inequívocos; o jogo sorteia 6 por partida.
Uso: python3 curriculos/jogos/gerar_pares.py
"""
import json
import os
import sys

MAX_LADO = 38
MAX_NOTA = 140
N_CONJUNTOS = 24
N_PARES = 10

# (id, titulo, instrucao, nivel, [(esquerda, direita, nota), ...])
CONJUNTOS = [
    ("par-sinais-abdome", "Sinais do abdome", "Ligue o sinal à doença", 1, [
        ("Sinal de Murphy", "Colecistite aguda",
         "Parada da inspiração ao palpar o ponto cístico."),
        ("Sinal de Rovsing", "Apendicite aguda",
         "Dor na fossa ilíaca direita ao comprimir a fossa ilíaca esquerda."),
        ("Sinal de Grey Turner", "Pancreatite necro-hemorrágica",
         "Equimose nos flancos por sangue retroperitoneal."),
        ("Sinal de Courvoisier", "Tumor periampular",
         "Vesícula palpável e indolor com icterícia: pense em câncer de cabeça de pâncreas."),
        ("Sinal de Jobert", "Pneumoperitônio",
         "Timpanismo na área hepática: ar livre sob o diafragma."),
        ("Sinal de Giordano", "Pielonefrite aguda",
         "Dor à punho-percussão lombar."),
        ("Sinal de Kehr", "Ruptura esplênica",
         "Dor referida no ombro esquerdo por sangue irritando o diafragma."),
        ("Sinal de Torres-Homem", "Abscesso hepático",
         "Dor localizada à percussão do hipocôndrio direito."),
        ("Sinal de Dance", "Intussuscepção intestinal",
         "Fossa ilíaca direita vazia à palpação na criança."),
        ("Sinal do candelabro", "Doença inflamatória pélvica",
         "Dor intensa à mobilização do colo uterino no toque vaginal."),
    ]),
    ("par-sinais-cardio", "Sinais cardiovasculares", "Ligue o sinal à doença", 2, [
        ("Tríade de Beck", "Tamponamento cardíaco",
         "Hipotensão, turgência jugular e bulhas abafadas."),
        ("Pulso de Corrigan", "Insuficiência aórtica",
         "Pulso em martelo d'água: ascensão e queda rápidas."),
        ("Pulso parvus et tardus", "Estenose aórtica",
         "Pulso pequeno e de subida lenta."),
        ("Sopro de Graham Steell", "Insuficiência pulmonar",
         "Sopro diastólico em foco pulmonar por hipertensão pulmonar."),
        ("Sopro de Carey Coombs", "Cardite reumática aguda",
         "Sopro mesodiastólico mitral por valvulite na febre reumática."),
        ("Sinal de Homans", "Trombose venosa profunda",
         "Dor na panturrilha à dorsiflexão do pé. Pouco sensível."),
        ("Sinal de Hamman", "Pneumomediastino",
         "Crepitação sincrônica com o batimento cardíaco."),
        ("Manchas de Janeway", "Endocardite infecciosa",
         "Máculas indolores em palmas e plantas."),
        ("Sinal de Rivero-Carvallo", "Insuficiência tricúspide",
         "Sopro que aumenta na inspiração profunda."),
        ("Clique mesossistólico", "Prolapso da valva mitral",
         "Clique seguido de sopro sistólico tardio."),
    ]),
    ("par-sinais-neuro", "Sinais neurológicos", "Ligue o sinal ao que indica", 2, [
        ("Sinal de Babinski", "Lesão do neurônio motor superior",
         "Extensão do hálux ao estimular a planta do pé."),
        ("Sinal de Romberg", "Ataxia sensitiva",
         "Perde o equilíbrio ao fechar os olhos: falha da propriocepção."),
        ("Sinal de Brudzinski", "Irritação meníngea",
         "Flexão do pescoço provoca flexão dos quadris e joelhos."),
        ("Sinal de Lasègue", "Radiculopatia lombar",
         "Dor irradiada ao elevar a perna estendida entre 30 e 70 graus."),
        ("Sinal de Tinel no punho", "Síndrome do túnel do carpo",
         "Percutir o nervo mediano causa formigamento nos dedos."),
        ("Sinal de Froment", "Lesão do nervo ulnar",
         "Flexiona o polegar para segurar papel: adutor do polegar fraco."),
        ("Sinal de Gowers", "Distrofia de Duchenne",
         "Usa as mãos nas coxas para levantar do chão: fraqueza proximal."),
        ("Sinal de Battle", "Fratura de base de crânio",
         "Equimose retroauricular."),
        ("Sinal de Chvostek", "Hipocalcemia",
         "Percutir o nervo facial causa contração da face."),
        ("Sinal de Hoover", "Fraqueza funcional",
         "Perna 'fraca' faz força ao elevar a outra: sugere causa não orgânica."),
    ]),
    ("par-sinais-reumato-derma", "Sinais em reumato e dermato", "Ligue o sinal à doença", 2, [
        ("Nódulos de Heberden", "Osteoartrite",
         "Nódulos ósseos nas interfalangeanas distais."),
        ("Pápulas de Gottron", "Dermatomiosite",
         "Pápulas violáceas sobre as articulações dos dedos."),
        ("Teste de Schober reduzido", "Espondilite anquilosante",
         "Menor flexão da coluna lombar."),
        ("Tofos", "Gota",
         "Depósitos de urato em orelhas, cotovelos e dedos."),
        ("Sinal de Nikolsky", "Pênfigo vulgar",
         "Pele se descola com leve fricção: bolha intraepidérmica."),
        ("Sinal de Auspitz", "Psoríase",
         "Sangramento puntiforme ao raspar a escama."),
        ("Sinal de Darier", "Mastocitose",
         "Lesão fica vermelha e urticada após fricção."),
        ("Teste de patergia positivo", "Doença de Behçet",
         "Pápula ou pústula surge após punção com agulha."),
        ("Sinal de Leser-Trélat", "Neoplasia maligna interna",
         "Surgimento súbito de muitas ceratoses seborreicas."),
        ("Eritema migrans", "Doença de Lyme",
         "Lesão em alvo que cresce a partir da picada do carrapato."),
    ]),
    ("par-antidotos", "Antídotos essenciais", "Ligue a intoxicação ao antídoto", 1, [
        ("Paracetamol", "N-acetilcisteína",
         "Repõe glutationa; melhor até 8 h após a ingestão."),
        ("Opioides", "Naloxona",
         "Antagonista opioide; reverte a depressão respiratória."),
        ("Benzodiazepínicos", "Flumazenil",
         "Antagonista; cuidado: pode causar convulsão em usuários crônicos."),
        ("Organofosforados", "Atropina",
         "Bloqueia o excesso muscarínico; seque as secreções."),
        ("Metanol", "Fomepizol ou etanol",
         "Bloqueiam a álcool desidrogenase e evitam o ácido fórmico."),
        ("Heparina não fracionada", "Protamina",
         "Liga-se à heparina e neutraliza seu efeito."),
        ("Varfarina", "Vitamina K",
         "Refaz os fatores II, VII, IX e X; no sangramento grave, somar complexo protrombínico."),
        ("Digoxina", "Anticorpo antidigoxina (Fab)",
         "Fragmentos Fab ligam a digoxina circulante."),
        ("Cianeto", "Hidroxocobalamina",
         "Forma cianocobalamina, eliminada na urina."),
        ("Ferro", "Deferoxamina",
         "Quelante que liga o ferro livre."),
    ]),
    ("par-antidotos-2", "Antídotos avançados", "Ligue a intoxicação ao antídoto", 3, [
        ("Dabigatrana", "Idarucizumabe",
         "Anticorpo que neutraliza a dabigatrana."),
        ("Isoniazida em dose tóxica", "Piridoxina",
         "Vitamina B6 trata as convulsões da intoxicação."),
        ("Betabloqueador", "Glucagon",
         "Aumenta o AMPc sem passar pelo receptor beta."),
        ("Metemoglobinemia", "Azul de metileno",
         "Reduz o ferro férrico da hemoglobina de volta a ferroso."),
        ("Sulfonilureia", "Octreotida",
         "Inibe a liberação de insulina e evita hipoglicemia recorrente."),
        ("Antidepressivo tricíclico", "Bicarbonato de sódio",
         "Indicado se QRS alargado ou arritmia."),
        ("Síndrome anticolinérgica", "Fisostigmina",
         "Anticolinesterásico que atravessa a barreira hematoencefálica."),
        ("Metotrexato", "Ácido folínico",
         "Leucovorina: resgate que dispensa a di-hidrofolato redutase."),
        ("Monóxido de carbono", "Oxigênio a 100%",
         "Encurta a meia-vida da carboxi-hemoglobina."),
        ("Sulfato de magnésio", "Gluconato de cálcio",
         "Antagoniza a toxicidade do magnésio (ex.: na pré-eclâmpsia)."),
    ]),
    ("par-micro-doenca", "Microrganismo e doença", "Ligue o agente à doença", 1, [
        ("Treponema pallidum", "Sífilis",
         "Espiroqueta; tratamento com penicilina."),
        ("Clostridioides difficile", "Colite pseudomembranosa",
         "Surge após uso de antibióticos; diarreia com pseudomembranas."),
        ("Helicobacter pylori", "Úlcera péptica",
         "Bacilo gram-negativo do estômago; também ligado ao câncer gástrico."),
        ("Mycobacterium leprae", "Hanseníase",
         "Bacilo de Hansen; afeta pele e nervos periféricos."),
        ("Leptospira interrogans", "Leptospirose",
         "Transmitida pela urina de ratos em enchentes."),
        ("Bordetella pertussis", "Coqueluche",
         "Tosse em crises com guincho inspiratório."),
        ("Corynebacterium diphtheriae", "Difteria",
         "Pseudomembrana acinzentada aderida na garganta."),
        ("Clostridium tetani", "Tétano",
         "Toxina causa rigidez, trismo e espasmos."),
        ("Trypanosoma cruzi", "Doença de Chagas",
         "Protozoário; pode causar cardiopatia e megavísceras."),
        ("Vírus Epstein-Barr", "Mononucleose infecciosa",
         "Febre, faringite, linfonodos e linfócitos atípicos."),
    ]),
    ("par-vetores", "Doenças tropicais e transmissores", "Ligue a doença ao transmissor", 2, [
        ("Malária", "Mosquito Anopheles",
         "Fêmea do Anopheles (carapanã) transmite o Plasmodium."),
        ("Dengue", "Mosquito Aedes aegypti",
         "Mosquito urbano, pica de dia; água parada."),
        ("Febre amarela silvestre", "Mosquitos Haemagogus e Sabethes",
         "Ciclo na mata, com macacos como hospedeiros."),
        ("Leishmaniose tegumentar", "Flebotomíneo (mosquito-palha)",
         "Lutzomyia; úlcera de bordas elevadas."),
        ("Doença de Chagas", "Triatomíneo (barbeiro)",
         "Na Amazônia, a via oral (açaí contaminado) é importante."),
        ("Oncocercose", "Simulídeo (pium)",
         "Filariose que afeta pele e olhos; foco em área Yanomami."),
        ("Febre do Oropouche", "Maruim (Culicoides paraensis)",
         "Arbovírus amazônico; quadro parecido com dengue."),
        ("Febre maculosa", "Carrapato Amblyomma",
         "Rickettsia rickettsii; alta letalidade sem tratamento precoce."),
        ("Esquistossomose", "Caramujo Biomphalaria",
         "Hospedeiro intermediário; cercárias penetram a pele na água."),
        ("Raiva humana", "Morcego hematófago",
         "Na Amazônia, principal transmissor em surtos humanos."),
    ]),
    ("par-tratamento", "Doença e tratamento de 1ª linha", "Ligue a doença ao tratamento", 2, [
        ("Sífilis primária", "Penicilina G benzatina",
         "2,4 milhões UI IM, dose única (PCDT IST, MS)."),
        ("Anafilaxia", "Adrenalina IM",
         "0,5 mg IM na coxa no adulto; repetir se preciso."),
        ("Hipotireoidismo primário", "Levotiroxina",
         "Tomar em jejum; ajustar pelo TSH."),
        ("Tuberculose pulmonar", "RIPE por 2 meses + RI por 4",
         "Rifampicina, isoniazida, pirazinamida e etambutol (esquema básico, MS)."),
        ("Hanseníase", "Poliquimioterapia única (PQT-U)",
         "Rifampicina, dapsona e clofazimina para todas as formas (MS)."),
        ("Pneumocistose", "Sulfametoxazol-trimetoprima",
         "Por 21 dias; corticoide se hipoxemia."),
        ("Gonorreia", "Ceftriaxona + azitromicina",
         "Ceftriaxona 500 mg IM + azitromicina 1 g VO (PCDT IST, MS)."),
        ("DM2 sem doença cardiovascular", "Metformina",
         "Primeira escolha na maioria dos casos (SBD)."),
        ("Hiperpotassemia com ECG alterado", "Gluconato de cálcio IV",
         "Estabiliza a membrana do miocárdio; não baixa o potássio."),
        ("Doença de Kawasaki", "Imunoglobulina IV + AAS",
         "Idealmente nos primeiros 10 dias; previne aneurisma coronariano."),
    ]),
    ("par-emergencias", "Emergências: primeira conduta", "Ligue a situação à conduta", 3, [
        ("Estado de mal epiléptico", "Benzodiazepínico IV ou IM",
         "Diazepam ou midazolam; depois, fenitoína ou similar."),
        ("Crise adrenal", "Hidrocortisona IV",
         "100 mg IV em bolus, mais soro fisiológico."),
        ("Hipoglicemia grave", "Glicose IV",
         "Sem acesso venoso: glucagon IM."),
        ("TSV estável", "Manobra vagal",
         "Se falhar: adenosina IV."),
        ("FV ou TV sem pulso", "Desfibrilação imediata",
         "Choque o quanto antes e RCP de alta qualidade."),
        ("Assistolia", "RCP e adrenalina, sem choque",
         "Ritmo não chocável; buscar causas reversíveis."),
        ("Torsades de pointes", "Sulfato de magnésio IV",
         "2 g IV; corrigir QT longo e distúrbios eletrolíticos."),
        ("Pneumotórax hipertensivo", "Descompressão torácica imediata",
         "Diagnóstico clínico: não esperar radiografia."),
        ("Tamponamento cardíaco", "Pericardiocentese",
         "Drena o líquido e libera o enchimento do coração."),
        ("Bradicardia sintomática instável", "Atropina IV",
         "1 mg IV; se falhar, marca-passo ou adrenalina/dopamina."),
    ]),
    ("par-classes-1", "Fármaco e classe: cardio e gastro", "Ligue o fármaco à classe", 1, [
        ("Losartana", "Bloqueador do receptor AT1 (BRA)",
         "Bloqueia a angiotensina II no receptor; não causa tosse."),
        ("Enalapril", "Inibidor da ECA",
         "Reduz a formação de angiotensina II."),
        ("Anlodipino", "Bloqueador de canal de cálcio",
         "Di-hidropiridínico; vasodilatador arterial."),
        ("Hidroclorotiazida", "Diurético tiazídico",
         "Age no túbulo contorcido distal."),
        ("Furosemida", "Diurético de alça",
         "Bloqueia o cotransportador Na-K-2Cl na alça de Henle."),
        ("Espironolactona", "Antagonista da aldosterona",
         "Diurético poupador de potássio."),
        ("Metoprolol", "Betabloqueador",
         "Beta-1 seletivo; usado em IC, angina e arritmias."),
        ("Atorvastatina", "Estatina",
         "Inibe a HMG-CoA redutase e reduz o LDL."),
        ("Omeprazol", "Inibidor da bomba de prótons",
         "Bloqueia a H+/K+ ATPase da célula parietal."),
        ("Clopidogrel", "Inibidor do receptor P2Y12",
         "Antiplaquetário; usado com AAS após stent."),
    ]),
    ("par-classes-2", "Fármaco e classe: endócrino e psiquiatria", "Ligue o fármaco à classe", 2, [
        ("Dapagliflozina", "Inibidor de SGLT2",
         "Aumenta a glicosúria; protege coração e rins."),
        ("Sitagliptina", "Inibidor de DPP-4",
         "Prolonga a ação das incretinas."),
        ("Semaglutida", "Agonista do receptor GLP-1",
         "Reduz glicemia e peso."),
        ("Glibenclamida", "Sulfonilureia",
         "Estimula a secreção de insulina; risco de hipoglicemia."),
        ("Pioglitazona", "Tiazolidinediona",
         "Aumenta a sensibilidade à insulina; retém líquido."),
        ("Fluoxetina", "ISRS",
         "Inibidor seletivo da recaptação de serotonina."),
        ("Venlafaxina", "IRSN",
         "Inibe a recaptação de serotonina e noradrenalina."),
        ("Amitriptilina", "Antidepressivo tricíclico",
         "Também usada em dor neuropática; efeitos anticolinérgicos."),
        ("Haloperidol", "Antipsicótico típico",
         "Bloqueador D2 potente; risco de sintomas extrapiramidais."),
        ("Rivaroxabana", "Inibidor direto do fator Xa",
         "Anticoagulante oral direto."),
    ]),
    ("par-efeitos-1", "Fármaco e efeito adverso", "Ligue o fármaco ao efeito", 2, [
        ("Enalapril", "Tosse seca",
         "Acúmulo de bradicinina; trocar por BRA."),
        ("Gentamicina", "Ototoxicidade",
         "Aminoglicosídeo; também nefrotóxico."),
        ("Clozapina", "Agranulocitose",
         "Exige hemograma periódico."),
        ("Etambutol", "Neurite óptica",
         "Perda de acuidade e de visão de cores (verde-vermelho)."),
        ("Sinvastatina", "Miopatia",
         "Dor muscular; raramente rabdomiólise."),
        ("Anlodipino", "Edema maleolar",
         "Vasodilatação arteriolar aumenta a pressão capilar."),
        ("Ciprofloxacino", "Ruptura de tendão",
         "Fluoroquinolona; risco maior no tendão de Aquiles e em idosos."),
        ("Espironolactona", "Ginecomastia",
         "Efeito antiandrogênico."),
        ("Lítio", "Diabetes insípido nefrogênico",
         "Rim não responde ao ADH; poliúria."),
        ("Cloranfenicol", "Síndrome do bebê cinzento",
         "Recém-nascido não conjuga o fármaco."),
    ]),
    ("par-efeitos-2", "Efeitos adversos marcantes", "Ligue o fármaco ao efeito", 3, [
        ("Amiodarona", "Tireoidopatia e fibrose pulmonar",
         "Rica em iodo; monitorar TSH e função pulmonar."),
        ("Isoniazida", "Neuropatia periférica",
         "Depleta vitamina B6; prevenir com piridoxina."),
        ("Isotretinoína", "Teratogenicidade grave",
         "Exige contracepção eficaz durante e após o uso."),
        ("Dapagliflozina", "Cetoacidose euglicêmica",
         "Cetoacidose com glicemia pouco elevada."),
        ("Sildenafila", "Visão azulada",
         "Inibe também a PDE6 da retina."),
        ("Rifampicina", "Urina e lágrima alaranjadas",
         "Efeito benigno; avisar o paciente."),
        ("Metoclopramida", "Distonia aguda",
         "Bloqueio D2; comum em jovens."),
        ("Heparina", "Trombocitopenia imune (HIT)",
         "Queda de plaquetas com trombose, 5 a 10 dias após o início."),
        ("Digoxina", "Visão amarelada",
         "Xantopsia: sinal de intoxicação digitálica."),
        ("Dapsona", "Metemoglobinemia",
         "Cianose com saturação baixa que não melhora com O2."),
    ]),
    ("par-nervos-perifericos", "Nervos periféricos", "Ligue o nervo à lesão ou função", 2, [
        ("Nervo radial", "Mão caída",
         "Perde a extensão do punho; fratura do úmero médio."),
        ("Nervo ulnar", "Mão em garra",
         "Paralisia dos interósseos e lumbricais mediais."),
        ("Nervo mediano", "Mão de bênção",
         "Lesão alta: não flexiona indicador e médio ao fechar a mão."),
        ("Nervo fibular comum", "Pé caído",
         "Lesão no colo da fíbula; marcha escarvante."),
        ("Nervo torácico longo", "Escápula alada",
         "Paralisia do serrátil anterior."),
        ("Nervo axilar", "Deltoide",
         "Abdução do ombro; lesão na fratura do colo do úmero."),
        ("Nervo musculocutâneo", "Bíceps braquial",
         "Flexão do cotovelo e supinação."),
        ("Nervo frênico", "Diafragma",
         "Raízes C3 a C5."),
        ("Nervo femoral", "Quadríceps femoral",
         "Extensão do joelho; reflexo patelar."),
        ("Nervo tibial", "Flexão plantar do pé",
         "Inerva gastrocnêmio e sóleo."),
    ]),
    ("par-nervos-cranianos", "Nervos cranianos", "Ligue o nervo à função", 2, [
        ("I - Olfatório", "Olfato",
         "Único nervo sensitivo que não passa pelo tálamo."),
        ("III - Oculomotor", "Ptose e midríase se lesado",
         "Olho 'para baixo e para fora' na lesão completa."),
        ("IV - Troclear", "Músculo oblíquo superior",
         "Lesão: diplopia ao descer escadas."),
        ("V - Trigêmeo", "Mastigação e sensibilidade facial",
         "Três ramos: oftálmico, maxilar e mandibular."),
        ("VI - Abducente", "Músculo reto lateral",
         "Lesão: não abduz o olho."),
        ("VII - Facial", "Mímica facial",
         "Paralisia de Bell: toda a hemiface."),
        ("VIII - Vestibulococlear", "Audição e equilíbrio",
         "Porções coclear e vestibular."),
        ("IX - Glossofaríngeo", "Gustação do 1/3 posterior",
         "Também leva a sensibilidade da faringe."),
        ("XI - Acessório", "Trapézio e esternocleidomastoideo",
         "Encolher os ombros e girar a cabeça."),
        ("XII - Hipoglosso", "Movimentos da língua",
         "Na lesão, a língua desvia para o lado lesado."),
    ]),
    ("par-hormonios", "Hormônio e onde é produzido", "Ligue o hormônio à origem", 1, [
        ("Insulina", "Células beta do pâncreas",
         "Reduz a glicemia."),
        ("Glucagon", "Células alfa do pâncreas",
         "Eleva a glicemia no jejum."),
        ("Cortisol", "Zona fasciculada da adrenal",
         "Glicocorticoide; regulado pelo ACTH."),
        ("Aldosterona", "Zona glomerulosa da adrenal",
         "Retém sódio e elimina potássio."),
        ("Calcitonina", "Células C da tireoide",
         "Células parafoliculares; marcador do carcinoma medular."),
        ("PTH", "Paratireoides",
         "Eleva o cálcio sérico."),
        ("Prolactina", "Adeno-hipófise",
         "Inibida pela dopamina."),
        ("Melatonina", "Glândula pineal",
         "Regula o ciclo sono-vigília."),
        ("Testosterona", "Células de Leydig",
         "Estimuladas pelo LH, no testículo."),
        ("Renina", "Aparelho justaglomerular",
         "Liberada no rim quando cai a perfusão renal."),
    ]),
    ("par-esfregaco", "Esfregaço de sangue", "Ligue o achado à condição", 3, [
        ("Esquizócitos", "Microangiopatia trombótica",
         "Hemácias fragmentadas: PTT, SHU ou CIVD."),
        ("Esferócitos", "Esferocitose hereditária",
         "Hemácias sem palidez central; teste de EMA."),
        ("Drepanócitos", "Anemia falciforme",
         "Hemácias em foice por HbS."),
        ("Corpúsculos de Heinz", "Deficiência de G6PD",
         "Hemoglobina oxidada precipitada."),
        ("Bastonetes de Auer", "Leucemia mieloide aguda",
         "Inclusões em forma de agulha nos blastos."),
        ("Neutrófilos hipersegmentados", "Anemia megaloblástica",
         "Seis ou mais lobos; falta de B12 ou folato."),
        ("Dacriócitos", "Mielofibrose",
         "Hemácias em lágrima."),
        ("Manchas de Gumprecht", "Leucemia linfocítica crônica",
         "Linfócitos frágeis que se rompem na lâmina."),
        ("Hemácias em rouleaux", "Mieloma múltiplo",
         "Empilhamento por excesso de proteína monoclonal."),
        ("Pontilhado basófilo", "Intoxicação por chumbo",
         "Grânulos de RNA ribossomal nas hemácias."),
    ]),
    ("par-marcadores", "Marcadores tumorais", "Ligue o marcador ao tumor", 2, [
        ("PSA", "Câncer de próstata",
         "Útil no seguimento; rastreio só com decisão compartilhada."),
        ("CA-125", "Câncer epitelial de ovário",
         "Pode subir em endometriose e gestação."),
        ("CA 19-9", "Adenocarcinoma de pâncreas",
         "Útil no seguimento; pouco útil no rastreio."),
        ("CEA", "Câncer colorretal",
         "Seguimento após cirurgia."),
        ("Alfafetoproteína", "Carcinoma hepatocelular",
         "Também eleva em tumores de saco vitelino."),
        ("Beta-hCG", "Coriocarcinoma",
         "Também útil na mola hidatiforme."),
        ("Calcitonina", "Carcinoma medular de tireoide",
         "Tumor das células C; pesquisar gene RET."),
        ("CA 15-3", "Câncer de mama",
         "Seguimento de doença metastática."),
        ("5-HIAA urinário", "Tumor carcinoide",
         "Metabólito da serotonina."),
        ("Proteína de Bence Jones", "Mieloma múltiplo",
         "Cadeias leves livres na urina."),
    ]),
    ("par-anticorpos", "Autoanticorpos", "Ligue o anticorpo à doença", 2, [
        ("Anti-DNA dupla hélice", "Lúpus eritematoso sistêmico",
         "Específico; acompanha a atividade da nefrite."),
        ("Anti-CCP", "Artrite reumatoide",
         "Muito específico; pode surgir antes dos sintomas."),
        ("Anticentrômero", "Esclerose sistêmica limitada",
         "Associado à forma CREST."),
        ("Anti-Jo-1", "Síndrome antissintetase",
         "Miosite, doença intersticial pulmonar e mãos de mecânico."),
        ("c-ANCA (anti-PR3)", "Granulomatose com poliangiite",
         "Vasculite de vias aéreas e rins."),
        ("TRAb", "Doença de Graves",
         "Anticorpo que estimula o receptor do TSH."),
        ("Antimitocôndria", "Colangite biliar primária",
         "Mulher com prurido e fosfatase alcalina alta."),
        ("Antitransglutaminase IgA", "Doença celíaca",
         "Dosar junto com IgA total."),
        ("Antirreceptor de acetilcolina", "Miastenia gravis",
         "Fraqueza que piora com o esforço; ptose."),
        ("Antimembrana basal glomerular", "Síndrome de Goodpasture",
         "Hemorragia pulmonar e glomerulonefrite."),
    ]),
    ("par-ecg", "Achados de ECG", "Ligue o achado à condição", 2, [
        ("Onda T apiculada", "Hiperpotassemia",
         "Primeiro sinal; depois QRS largo."),
        ("Onda U proeminente", "Hipopotassemia",
         "Com achatamento da onda T."),
        ("PR curto e onda delta", "Wolff-Parkinson-White",
         "Pré-excitação por via acessória."),
        ("Onda épsilon", "Cardiomiopatia arritmogênica do VD",
         "Entalhe no fim do QRS em V1 a V3."),
        ("Onda J de Osborn", "Hipotermia",
         "Entalhe no ponto J."),
        ("Supra de ST difuso e infra de PR", "Pericardite aguda",
         "Supra côncavo em várias derivações."),
        ("Padrão S1Q3T3", "Tromboembolismo pulmonar",
         "Pouco sensível; taquicardia sinusal é mais comum."),
        ("Ondas F em dente de serra", "Flutter atrial",
         "Melhor vistas em DII, DIII e aVF."),
        ("RR irregular sem onda P", "Fibrilação atrial",
         "Ritmo irregularmente irregular."),
        ("Supra de ST em cúpula em V1-V2", "Síndrome de Brugada",
         "Padrão tipo 1; risco de morte súbita."),
    ]),
    ("par-radiologia", "Sinais radiológicos", "Ligue o sinal à doença", 3, [
        ("Sinal de Westermark", "Tromboembolismo pulmonar",
         "Área de oligoemia distal ao êmbolo."),
        ("Linhas B de Kerley", "Congestão pulmonar",
         "Linhas horizontais nas bases por edema intersticial."),
        ("Sinal do grão de café", "Volvo de sigmoide",
         "Alça sigmoide muito dilatada em U invertido."),
        ("Lesão em miolo de maçã", "Câncer colorretal",
         "Estenose anular no enema opaco."),
        ("Bico de pássaro no esofagograma", "Acalasia",
         "Afilamento distal com esôfago dilatado."),
        ("Coluna em bambu", "Espondilite anquilosante",
         "Sindesmófitos unindo as vértebras."),
        ("Crânio em sal e pimenta", "Hiperparatireoidismo",
         "Reabsorção óssea puntiforme."),
        ("Coração em bota", "Tetralogia de Fallot",
         "Ponta elevada e arco pulmonar escavado."),
        ("Sinal do 3 na aorta", "Coarctação da aorta",
         "Também há erosão dos arcos costais."),
        ("Sinal da dupla bolha", "Atresia duodenal",
         "Estômago e duodeno cheios de ar; associada à Down."),
    ]),
    ("par-genetica", "Síndromes genéticas", "Ligue a síndrome à alteração", 2, [
        ("Síndrome de Down", "Trissomia do 21",
         "Causa genética mais comum de deficiência intelectual."),
        ("Síndrome de Edwards", "Trissomia do 18",
         "Mãos fechadas com dedos sobrepostos; pés em mata-borrão."),
        ("Síndrome de Patau", "Trissomia do 13",
         "Fenda labiopalatina, polidactilia, holoprosencefalia."),
        ("Síndrome de Turner", "Cariótipo 45,X",
         "Baixa estatura, pescoço alado, coarctação da aorta."),
        ("Síndrome de Klinefelter", "Cariótipo 47,XXY",
         "Homem alto, testículos pequenos, infertilidade."),
        ("Síndrome do X frágil", "Expansão CGG no gene FMR1",
         "Deficiência intelectual, orelhas grandes, macro-orquidia."),
        ("Síndrome de Marfan", "Mutação no gene FBN1",
         "Fibrilina-1; risco de dissecção de aorta."),
        ("Doença de Huntington", "Expansão CAG no gene HTT",
         "Coreia e demência; herança autossômica dominante."),
        ("Síndrome de DiGeorge", "Deleção 22q11.2",
         "Hipocalcemia, cardiopatia e timo ausente."),
        ("Síndrome do miado do gato", "Deleção 5p",
         "Choro agudo como miado; microcefalia."),
    ]),
    ("par-vacinas", "Vacinas e idade (PNI)", "Ligue a vacina à idade", 1, [
        ("BCG", "Ao nascer",
         "Dose única, intradérmica, no braço direito."),
        ("Meningocócica C (1ª dose)", "3 meses",
         "Doses aos 3 e 5 meses; reforço aos 12 meses com ACWY."),
        ("Pentavalente", "2, 4 e 6 meses",
         "Difteria, tétano, coqueluche, Hib e hepatite B."),
        ("Febre amarela (1ª dose)", "9 meses",
         "Reforço aos 4 anos."),
        ("Tríplice viral (1ª dose)", "12 meses",
         "Sarampo, caxumba e rubéola."),
        ("Hepatite A", "15 meses",
         "Dose única na rotina infantil."),
        ("HPV", "9 a 14 anos",
         "Meninas e meninos; previne câncer de colo e outros."),
        ("dTpa na gestação", "A partir de 20 semanas",
         "Em toda gestação; protege o bebê da coqueluche."),
        ("dT no adulto", "Reforço a cada 10 anos",
         "Após esquema completo; antes se ferimento de risco."),
        ("Influenza", "Todo ano, na campanha",
         "Vírus muda; vacina atualizada a cada ano."),
    ]),
]


def validar(conjuntos):
    erros = []
    if len(conjuntos) != N_CONJUNTOS:
        erros.append(f"esperado {N_CONJUNTOS} conjuntos, há {len(conjuntos)}")
    ids = [c["id"] for c in conjuntos]
    if len(set(ids)) != len(ids):
        erros.append("ids repetidos")
    for c in conjuntos:
        cid = c["id"]
        if not cid.isascii():
            erros.append(f"{cid}: id não ASCII")
        if c["nivel"] not in (1, 2, 3):
            erros.append(f"{cid}: nível inválido")
        pares = c["pares"]
        if len(pares) != N_PARES:
            erros.append(f"{cid}: {len(pares)} pares")
        esq = [p[0] for p in pares]
        dir_ = [p[1] for p in pares]
        for lado, nome in ((esq, "esquerda"), (dir_, "direita")):
            norm = [s.casefold() for s in lado]
            if len(set(norm)) != len(norm):
                erros.append(f"{cid}: repetido na {nome}")
        if set(s.casefold() for s in esq) & set(s.casefold() for s in dir_):
            erros.append(f"{cid}: item igual nos dois lados")
        for s in esq + dir_:
            if len(s) > MAX_LADO:
                erros.append(f"{cid}: '{s}' tem {len(s)} caracteres")
        for s in esq:
            nota = c["notas"].get(s)
            if not nota:
                erros.append(f"{cid}: sem nota para '{s}'")
            elif len(nota) > MAX_NOTA:
                erros.append(f"{cid}: nota de '{s}' tem {len(nota)} car.")
        if set(c["notas"]) - set(esq):
            erros.append(f"{cid}: notas sobrando")
    return erros


def main():
    conjuntos = []
    for cid, titulo, instrucao, nivel, itens in CONJUNTOS:
        conjuntos.append({
            "id": cid,
            "titulo": titulo,
            "instrucao": instrucao,
            "nivel": nivel,
            "pares": [[e, d] for e, d, _ in itens],
            "notas": {e: n for e, _, n in itens},
        })
    erros = validar(conjuntos)
    if erros:
        print("\n".join(erros))
        sys.exit(1)
    destino = os.path.join(os.path.dirname(os.path.abspath(__file__)), "pares.json")
    with open(destino, "w", encoding="utf-8") as f:
        json.dump(conjuntos, f, ensure_ascii=False, indent=1)
        f.write("\n")
    print(f"OK: {len(conjuntos)} conjuntos, "
          f"{sum(len(c['pares']) for c in conjuntos)} pares -> {destino}")


if __name__ == "__main__":
    main()
